/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Barcelona(props) {
  const { nodes, materials } = useGLTF("/barcelona_very_small.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.12, -2.53]} scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_1.geometry}
          material={materials.wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_2.geometry}
          material={materials.roof}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_3.geometry}
          material={materials["7aa7ba"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_4.geometry}
          material={materials.grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_5.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_6.geometry}
          material={materials.white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_7.geometry}
          material={materials.b38875}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_8.geometry}
          material={materials["635b50"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_9.geometry}
          material={materials["809296"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_10.geometry}
          material={materials["9a6251"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.map_2osm_buildings_11.geometry}
          material={materials.tan}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_water.geometry}
        material={materials.water}
        position={[0, 0.12, -2.53]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_areas_pedestrian.geometry}
        material={materials.areas_pedestrian}
        position={[0, 0.12, -2.53]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_areas_footway.geometry}
        material={materials.areas_footway}
        position={[0, 0.12, -2.53]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_forest.geometry}
        material={materials.forest}
        position={[0, 0.12, -2.53]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.map_2osm_vegetation.geometry}
        material={materials.vegetation}
        position={[0, 0.12, -2.53]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/barcelona_very_small.gltf");
