# Generated by Django 4.1.2 on 2022-10-27 14:31

from django.db import migrations, models
import niet.utils.tokens


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_user_identifier_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=niet.utils.tokens.random_id_field, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
